In [1]:
import pandas as pd
import pickle
import numpy as np

from syto.data.pseudobulk_generator import PseudobulkGenerator

%load_ext autoreload
%autoreload 2

In [2]:
predicted_reads = pickle.load(
    open(
        "Data/training_data/methylBert_Loyfer_205files_U25_attentionClassifier_hg38_dmr_ctype_label_mincpg_4_minlen_10_no_data_leak_d041_postfiltered_min_length_50_hard_labels_focal_loss_for_plotting/predicted_reads.pkl",
        "rb",
    )
)

In [3]:
predicted_reads.keys()

dict_keys(['train', 'valid', 'test'])

In [4]:
train_predicted_reads = predicted_reads["train"]

In [5]:
train_predicted_reads.keys()

Index(['chr', 'read_name', 'trimmed_start', 'trimmed_end', 'pattern', 'seq',
       'name', 'region_start', 'region_end', 'original_label', 'label',
       'soft_label', 'M', 'U', 'NCPGS', 'M_rate', 'record_M', 'record_U',
       'record_X', 'dmr_ctype', 'dmr_ctype_matched', 'dmr_ctype_label',
       'pattern_len', 'prediction_0', 'prediction_1', 'prediction_2',
       'prediction_3', 'prediction_4', 'prediction_5', 'prediction_6',
       'prediction_7', 'prediction_8', 'prediction_9', 'prediction_10',
       'prediction_11', 'prediction_12', 'prediction_13', 'prediction_14',
       'prediction_15', 'prediction_16', 'prediction_17', 'prediction_18',
       'prediction_19', 'prediction_20', 'prediction_21', 'prediction_22',
       'prediction_23', 'prediction_24', 'prediction_25', 'prediction_26',
       'prediction_27', 'prediction_28', 'prediction_29', 'prediction_30',
       'prediction_31', 'prediction_32', 'prediction_33', 'prediction_34',
       'prediction_35', 'prediction_36', 'prediction_37', 'prediction_38',
       'prediction_39'],
      dtype='object')

In [6]:
train_predicted_reads["dmr_ctype_label"].value_counts()

dmr_ctype_label
20    149915
17    132611
29    126974
38    109426
2     104153
8     100427
23     98282
26     94518
5      93058
36     92189
18     90726
31     87293
6      85822
22     82900
21     81209
14     80585
34     74529
30     73512
15     73222
3      70580
35     69629
24     68997
9      67752
27     67440
10     66357
7      66129
1      65902
33     64252
19     60524
16     58379
12     57261
32     56701
13     52941
4      50136
28     50123
25     45443
0      25202
37     10670
11      4345
Name: count, dtype: int64

In [7]:
indices_per_class_and_grg = train_predicted_reads.groupby(
    ["original_label", "dmr_ctype_label"]
).indices

In [8]:
train_predicted_reads[["M", "U"]].head()

   M  U
0  5  0
1  6  0
2  6  0
3  6  0
4  5  1

In [9]:
train_predicted_reads.columns

Index(['chr', 'read_name', 'trimmed_start', 'trimmed_end', 'pattern', 'seq',
       'name', 'region_start', 'region_end', 'original_label', 'label',
       'soft_label', 'M', 'U', 'NCPGS', 'M_rate', 'record_M', 'record_U',
       'record_X', 'dmr_ctype', 'dmr_ctype_matched', 'dmr_ctype_label',
       'pattern_len', 'prediction_0', 'prediction_1', 'prediction_2',
       'prediction_3', 'prediction_4', 'prediction_5', 'prediction_6',
       'prediction_7', 'prediction_8', 'prediction_9', 'prediction_10',
       'prediction_11', 'prediction_12', 'prediction_13', 'prediction_14',
       'prediction_15', 'prediction_16', 'prediction_17', 'prediction_18',
       'prediction_19', 'prediction_20', 'prediction_21', 'prediction_22',
       'prediction_23', 'prediction_24', 'prediction_25', 'prediction_26',
       'prediction_27', 'prediction_28', 'prediction_29', 'prediction_30',
       'prediction_31', 'prediction_32', 'prediction_33', 'prediction_34',
       'prediction_35', 'prediction_36', 'prediction_37', 'prediction_38',
       'prediction_39'],
      dtype='object')

In [19]:
result = PseudobulkGenerator.generate_single_pseudobulk(
    n_reads_to_sample=39 * 40,
    n_gr_groups=39,
    indices_per_class_and_grg=indices_per_class_and_grg,
    read_df=train_predicted_reads,
    target_proportions=np.ones(40) / 40,
    grg_grouping_columns=["dmr_ctype", "dmr_ctype_label"],
)

In [20]:
result["aggregated_features"]

,dmr_ctype,dmr_ctype_label,n_reads,total_weight,label,prediction_0_wavg,prediction_1_wavg,prediction_2_wavg,prediction_3_wavg,prediction_4_wavg,...,prediction_30_wavg,prediction_31_wavg,prediction_32_wavg,prediction_33_wavg,prediction_34_wavg,prediction_35_wavg,prediction_36_wavg,prediction_37_wavg,prediction_38_wavg,prediction_39_wavg
0,Adipocytes,0,42,184,0,0.037766,0.005284,0.005258,0.005489,0.002452,...,0.006493,0.005752,0.006342,0.006614,0.009445,0.004920,0.003892,0.007832,0.005021,0.774265
1,Bladder-Ep,1,40,205,1,0.005422,0.044901,0.003253,0.002882,0.001469,...,0.002950,0.001789,0.002792,0.005078,0.006007,0.002670,0.006343,0.006967,0.006708,0.807630
2,Blood-B,2,36,189,39,0.003940,0.003525,0.052560,0.001512,0.006127,...,0.005235,0.004711,0.001647,0.001183,0.002835,0.004478,0.002891,0.005338,0.001549,0.812605
3,Blood-Granul,3,28,136,39,0.006320,0.002454,0.001911,0.026024,0.002695,...,0.006003,0.003139,0.006193,0.003200,0.007385,0.003151,0.006696,0.005530,0.004656,0.834790
4,Blood-Mono+Macro,4,34,175,39,0.002561,0.002188,0.008024,0.003723,0.099516,...,0.002599,0.002056,0.000705,0.002155,0.006769,0.001576,0.005248,0.003086,0.000912,0.742836
5,Blood-NK,5,44,251,39,0.003829,0.003789,0.004504,0.003994,0.002088,...,0.005245,0.005966,0.002790,0.003244,0.008864,0.003719,0.001087,0.003054,0.006182,0.803890
6,Blood-T,6,43,225,39,0.001162,0.002283,0.003945,0.001893,0.013165,...,0.001575,0.000694,0.001035,0.003692,0.005073,0.001113,0.004656,0.001139,0.001908,0.734375
7,Bone-Osteob,7,46,256,39,0.006003,0.004211,0.001697,0.003404,0.000401,...,0.002662,0.005232,0.006850,0.003365,0.002997,0.004139,0.003888,0.003919,0.006149,0.831833
8,Breast-Basal-Ep,8,44,274,39,0.007112,0.005181,0.004906,0.003070,0.001959,...,0.003438,0.004131,0.003398,0.003617,0.006731,0.002646,0.002525,0.003601,0.003631,0.830128
9,Breast-Luminal-Ep,9,31,136,39,0.009209,0.003355,0.002644,0.004497,0.001477,...,0.006816,0.004726,0.004878,0.003685,0.004392,0.002781,0.004143,0.006028,0.005056,0.821298
10,Colon-Ep,10,43,198,39,0.005483,0.004581,0.005151,0.004475,0.006614,...,0.001725,0.001844,0.003064,0.004139,0.005111,0.001523,0.003858,0.008231,0.002313,0.765083
11,Colon-Fibro,11,45,265,39,0.008456,0.004140,0.005506,0.004583,0.002010,...,0.007002,0.006747,0.005726,0.003670,0.006438,0.004108,0.003066,0.005771,0.004943,0.820013
12,Dermal-Fibro,12,42,242,39,0.005379,0.001994,0.002970,0.003225,0.000549,...,0.008011,0.005400,0.005838,0.001903,0.005053,0.005937,0.002002,0.001615,0.004975,0.852667
13,Endothel,13,34,170,39,0.002320,0.006018,0.003580,0.002489,0.011646,...,0.001691,0.000990,0.001652,0.002755,0.002660,0.001307,0.007370,0.005698,0.001375,0.720208
14,Epid-Kerat,14,42,240,39,0.005196,0.001000,0.001874,0.003329,0.001137,...,0.004810,0.005034,0.003846,0.003557,0.003104,0.004731,0.002678,0.001714,0.004015,0.859056
15,Eryth-prog,15,87,473,39,0.005860,0.002354,0.008038,0.004083,0.006168,...,0.005559,0.005757,0.004117,0.003105,0.005362,0.002093,0.002913,0.004329,0.002565,0.816542
16,Fallopian-Ep,16,40,177,39,0.006481,0.001560,0.005081,0.004392,0.002098,...,0.005596,0.004615,0.004274,0.002685,0.005933,0.004207,0.004730,0.003922,0.001520,0.837792
17,Gallbladder,17,42,249,39,0.002549,0.001083,0.001019,0.003098,0.000375,...,0.003483,0.004835,0.004873,0.001970,0.001816,0.003310,0.002447,0.001441,0.003221,0.879258
18,Gastric-Ep,18,34,181,39,0.001006,0.007518,0.004558,0.001435,0.003375,...,0.000937,0.001204,0.001395,0.001886,0.002018,0.001213,0.002188,0.005047,0.002039,0.774196
19,Head-Neck-Ep,19,38,183,39,0.001902,0.003319,0.003385,0.002290,0.012725,...,0.001138,0.001265,0.000972,0.005941,0.001899,0.001270,0.008411,0.005647,0.001568,0.762573
20,Heart-Cardio,20,36,227,39,0.002575,0.003220,0.005230,0.002875,0.001971,...,0.003094,0.002588,0.003214,0.002329,0.005106,0.003025,0.004797,0.003649,0.003496,0.847427
21,Heart-Fibro,21,41,223,39,0.003148,0.002756,0.002155,0.004725,0.002735,...,0.004526,0.003509,0.004725,0.004089,0.003651,0.001242,0.005460,0.007092,0.003904,0.820649
22,Kidney-Ep,22,36,201,39,0.002837,0.003301,0.002890,0.001681,0.005331,...,0.000676,0.001621,0.002033,0.004564,0.005757,0.001692,0.004745,0.004475,0.001003,0.810811
23,Liver-Hep,23,33,171,39,0.002130,0.007771,0.007502,0.002324,0.008602,...,0.003530,0.001829,0.001477,0.002686,0.006025,0.001585,0.004142,0.004079,0.004111,0.728439
24,Lung-Ep-Alveo,24,39,222,39,0.006787,0.001525,0.010216,0.002576,0.008053,...,0.002735,0.003254,0.002544,0.004196,0.008087,0.002894,0.005220,0.005385,0.001999,0.794187
25,Lung-Ep-Bron,25,40,193,39,0.005322,0.004989,0.009429,0.003579,0.003664,...,0.002588,0.007315,0.002518,0.002568,0.003110,0.002249,0.001922,0.013667,0.002364,0.786579
26,Neuron,26,36,228,39,0.004827,0.004277,0.007506,0.002193,0.006005,...,0.001913,0.000842,0.002068,0.004361,0.004244,0.004194,0.005908,0.003305,0.001728,0.789184
27,Oligodend,27,57,324,39,0.005946,0.002221,0.004903,0.003095,0.003633,...,0.005496,0.003775,0.002062,0.002785,0.003426,0.002853,0.003059,0.005004,0.001445,0.847800
28,Ovary-Ep,28,35,194,39,0.002497,0.009919,0.004262,0.003550,0.001389,...,0.004791,0.003082,0.004575,0.004572,0.003120,0.002647,0.005871,0.008848,0.005827,0.796066
29,Pancreas-Acinar,29,36,208,39,0.002815,0.004659,0.007101,0.000737,0.005469,...,0.001225,0.003744,0.001330,0.003386,0.002475,0.002150,0.001839,0.002427,0.002109,0.822051
30,Pancreas-Alpha,30,41,188,39,0.005088,0.001879,0.007709,0.003796,0.001909,...,0.033220,0.004931,0.003713,0.001626,0.004172,0.004951,0.003947,0.002558,0.004561,0.841581
31,Pancreas-Beta,31,47,237,39,0.005032,0.001691,0.007730,0.002538,0.001622,...,0.005927,0.027451,0.003098,0.002413,0.002725,0.003841,0.001018,0.002956,0.002755,0.840751
32,Pancreas-Delta,32,34,150,39,0.007613,0.002541,0.002509,0.006023,0.000440,...,0.005611,0.004494,0.023638,0.003473,0.004339,0.004060,0.003709,0.004565,0.006463,0.830420
33,Pancreas-Duct,33,25,124,39,0.007337,0.003676,0.001106,0.003182,0.002015,...,0.002128,0.002764,0.003481,0.029601,0.006922,0.003036,0.005307,0.003853,0.004079,0.840494
34,Prostate-Ep,34,33,166,39,0.005712,0.004660,0.002893,0.004960,0.005059,...,0.003203,0.002352,0.002718,0.003686,0.044302,0.001688,0.002475,0.002316,0.003803,0.825283
35,Skeletal-Musc,35,50,270,39,0.005909,0.002868,0.006729,0.002583,0.000855,...,0.007662,0.003646,0.003970,0.003214,0.002771,0.022747,0.005774,0.002738,0.003984,0.851958
36,Small-Int-Ep,36,33,177,39,0.002834,0.004345,0.002515,0.004037,0.002960,...,0.003091,0.000921,0.002804,0.003517,0.003856,0.003729,0.046685,0.004428,0.002739,0.841346
37,Smooth-Musc,37,35,175,39,0.011299,0.007800,0.009026,0.006724,0.003426,...,0.004822,0.004375,0.005569,0.004492,0.004716,0.003786,0.007954,0.042328,0.003127,0.717709
38,Thyroid-Ep,38,38,235,39,0.004029,0.007093,0.001149,0.004337,0.000455,...,0.006188,0.003768,0.005927,0.004857,0.004635,0.003695,0.002413,0.002025,0.034240,0.839408

In [21]:
result["n_samples_per_class_per_grg"]

array([[1, 0, 1, ..., 0, 1, 0],
       [1, 1, 1, ..., 2, 0, 1],
       [2, 2, 0, ..., 0, 2, 1],
       ...,
       [1, 2, 0, ..., 1, 2, 2],
       [2, 1, 1, ..., 0, 1, 1],
       [4, 0, 4, ..., 0, 1, 2]])

In [22]:
result["n_samples_per_class_per_grg"].sum()

np.int64(1560)

In [24]:
result["aggregated_features"]["n_reads"].sum()

np.int64(1560)